export const SIGN_UP_URL = 'http://localhost:4000/auth/signup'
export const GET_PROFILE_URL = 'http://localhost:4000/auth'
export const LOGIN_URL = 'http://localhost:4000/auth/login'
export const ADD_CONTACT_URL = 'http://localhost:4000/users/addcontact'
export const ADD_TODO_URL = 'http://localhost:4000/todo/addtodos'
